server:
  port: 8085
  servlet:
    context-path: /book
spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/book-service?authSource=admin
openapi:
  service:
    api-docs: book-api-service
    server: http://localhost:8085/book
    title: Book API Service
    version: 1.0.0